### ISSUE TITLE
Bug list for new 1.3.1 release

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-iphoneos#110]
- [x] Generate certificate view is off-center
- [x] Text fields when adding a favourite server are not resized to fit the table view cell.
- [ ] There is no transition when connecting to a server, like there was previously.
- [x] Messages in the messages tab do not fill the screen.
- [x] The text field when adding an access token does not fill the UITableViewCell
- [x] When generating a certificate in the simulator, it isn't stored. (Maybe happens on device, too?)

**Comment by triwav** [comment]
Not sure if I'm doing something wrong but the app seems to start with your mic muted but doesn't show like it is. Muting and then unmuting seems to make it work properly.

**Comment by mkrautz** [comment]
@triwav Haven't been able to reproduce that... Hm.

**Comment by triwav** [comment]
Maybe I'm just not speaking loud about at first? It's always sound activated right?

**Comment by mkrautz** [comment]
@triwav You can choose in Preferences how audio is sent. (Voice activated, Push-to-talk, Continuous)

**Comment by dakira** [comment]
Everything works perfectly fine for me. Go for release. ;)

**Comment by mkrautz** [comment]
@dakira I have submitted current Git master for review. If it gets approved, at least there is something ready for the iOS 11 release, maybe even GM.

Also in TestFlight review...

**Comment by mkrautz** [comment]
OK. Rejected because I accidentally put "Built in 64-bit mode to make the app work on iOS 11" in the release notes. (You can't mention pre-release software on the App Store...).

Re-submitted with tweaked wording.

**Comment by mkrautz** [comment]
Current Git master is now on the App Store as 1.3.1.
