### ISSUE TITLE
iOS app - iRig not handled well.

### ISSUE THREAD

**Issue by supawiz6991** [mumble-voip/mumble-iphoneos#127]
The mumble app doesn't seem to work well with the "iRig for mic" adapter for the ipad/ipod/iphone. 
My exact steps:
Plug in irig device
start mumble app
connect to server
when i talk sometimes my audio is transmitted and sometimes it isnt.
self_muting/self_unmuting restores my mic audio for a short period before cutting out.
The mic audio will cut in and out.
Mic audio also has an echo problem when using the irig /w mumble.

When tested with skype the irig worked flawlessly. I'm not sure if this is something you are willing to fix/support the irig for mic adapter, but if you would, I would greatly appreciate it! I am also willing to provide more feedback on the issues with the device if needed!

**Comment by davidebeatrici** [comment]
@supawiz6991 Is the issue fixed?

**Comment by supawiz6991** [comment]
> @supawiz6991 Is the issue fixed?

Not that I know of. I'm also no longer at the company I was with when I encountered this problem and thus do not have the hardware to check for it.
