### ISSUE TITLE
incompatibility with iRig

### ISSUE THREAD

**Issue by supawiz6991** [mumble-voip/mumble-iphoneos#84]
Mumble for iOS doesn't handle the iRig device well. When the iRig is connected and mumble set to continuous audio, my audio cuts in and out almost like mumble thinks the device is disconnecting/reconnecting repeatedly. In some cases audio doesn't work at all.

iRig -> http://www.amazon.com/IK-Multimedia-iPhone-Android-Devices/dp/B007534LFK/ref=sr_1_4?ie=UTF8&qid=1438696119&sr=8-4&keywords=irig+2

If needed, I'd be willing to donate the funds for the purchase of one of these if needed to resolve this :) :+1: 

Latest Version of Mumble for iOS
Testing with iOS 7.1.1 - 8.4

**Comment by mkrautz** [comment]
Hello @supawiz6991 

I'm willing to help take a look at this, but I don't own the hardware.

I've created an Amazon wishlist with the item on it:
http://www.amazon.co.uk/registry/wishlist/25AKONNY0QWGE

Do I need an XLR microphone to test it, though? I don't have one either. (So if needed, I can add that to the wishlist as well).

**Comment by supawiz6991** [comment]
Yep, you will need an XLR Mic and cable. These two should work:
http://www.amazon.com/CBI-MLC20-Microphone-Cable-Foot/dp/B000VJJQUU/ref=sr_1_6?ie=UTF8&qid=1440611678&sr=8-6&keywords=XLR+Mic

http://www.amazon.com/Pyle-Pro-PDMIC58-Professional-Handheld-Microphone/dp/B003GEBGA0/ref=sr_1_1?ie=UTF8&qid=1440611678&sr=8-1&keywords=XLR+Mic

Add it to the list and I'll get it taken care of! :)

**Comment by mkrautz** [comment]
@supawiz6991 Added equivalently priced items from Amazon.co.uk, since that's where the wishlist lives. :-)

**Comment by supawiz6991** [comment]
Went to buy the gear for you but you didnt enable third party address sharing. Once you enable that I can buy those items for you.

http://www.amazon.com/gp/help/customer/display.html?nodeId=3058771

**Comment by mkrautz** [comment]
I have now added an address, but no enabled third-party address sharing (which seems to be for if you purchase from the marketplace instead of Amazon). Let me know if this works, or if I'll have to enable it.

**Comment by supawiz6991** [comment]
Purchased and on its way to you (Should arrive in 3-5 days)! Thanks in advance for looking into this issue and enjoy the gear!

**Comment by supawiz6991** [comment]
Have you had any luck with this yet? :)

**Comment by mkrautz** [comment]
Hi @supawiz6991,

Sorry for being a bit uncommunicative...

I can confirm that I have received the iRig, mic and cable.

I have not yet had time to play with it yet.

I hope to find time later in the week, or during the weekend. Thanks for your patience, and for the hardware to test on... Much appreciated.

**Comment by supawiz6991** [comment]
No Worries :) Your willing to look into this issue for me and chances are I'm the only one affected by it (or at least the only one who's made and issue about it) so I can't complain! You could have just said "oh well" and been done with it sooo yeah...thanks! :) :+1:

**Comment by supawiz6991** [comment]
heyo! Just wanted to check in and see if you have had a chance to look at this yet!

**Comment by supawiz6991** [comment]
bump :)

**Comment by mkrautz** [comment]
I have had a chance to look at it, and I am in the process of trying to fix it...

I was able to reproduce it, but it doesn't -- at least for now -- seem restricted to the iRig.

**Comment by supawiz6991** [comment]
Thanks for the update! Very interesting...that's the only device I've notice the issue with but looks like the fix will have a wider benefit than I originally thought!

**Comment by supawiz6991** [comment]
Heyo! Wanted to check in and see if you had been able to finish the fix for this?

**Comment by supawiz6991** [comment]
Hi @mkrautz !
Any update on a fix for this?

**Comment by supawiz6991** [comment]
Any update on this?

**Comment by mkrautz** [comment]
Apologies for the lack of communication.

All my time to work on anything Mumble-related as of late has been on the main desktop client.
I hope to have some spare time to hack on this again soon. :-(

**Comment by supawiz6991** [comment]
Hey @mkrautz any update?

**Comment by mkrautz** [comment]
Unfortunately, the situation hasn't changed since last time.

And boy do I feel terrible about it. Especially since you've donated a significant amount in order to have the bug fixed.

I hope to look into this very soon. So sorry.

**Comment by supawiz6991** [comment]
Hey, any change on this?

Also, fyi, while setting up a new ipad at work, I got a popup from apple regarding the mumble app that said "This app will not work for ios 11. The developer will need to update it"

Do you see a future for the mobile app? I'm hoping there is because at this point (IMO) there is no good mobile app alternative. I do understand though that 1. these are free apps and 2. you are only one person and can only do so much development on your own...so if the app does have to die for now I do understand. :)

**Comment by nixCodeX** [comment]
I can help develop however I am not a member of the developer program so won't be able to publish, I do have the iOS 11 public beta and I'll endeavour to update the app and submit a pull request with enough time before iOS 11 launches.

**Comment by mkrautz** [comment]
I believe we've already converted the code to build in 64-bit mode.

The remaining problems would be to ensure we scale to newer devices, new icons/launchscreens, and anything else that is now required to get into the App Store.

Any help is appreciated!

**Comment by supawiz6991** [comment]
I'm happy to hear the app is under a good amount of development!!!!

Any idea if a fix for this issue will be in the next release? I would love to be able to dump skype and return to mumble :)
