### ISSUE TITLE
App-Scaling

### ISSUE THREAD

**Issue by cjt3007** [mumble-voip/mumble-iphoneos#96]
It appears as though this application was written with hard-coded screen sizes in mind - but with so many different iOS device sizes out there now, it'd be nice to be able to have the app scale to fit better. Also... is the development on this app still alive?

**Comment by mkrautz** [comment]
Not completely dead, but very inactive as of late!

This issue is something that would definitely get tackled once I get some more time to commit to the iOS app.

**Comment by mkrautz** [comment]
This was fixed by the just-released 1.3.1.
