### ISSUE TITLE
Crashes and high CPU on iOS10

### ISSUE THREAD

**Issue by dakira** [mumble-voip/mumble-iphoneos#99]
When opening the app I get a system warning like "the developer needs to update this app". When using the app I get disconnected very often and iPhone heats up until it crashes.

I have this behavior on iOS 10.1.1 using an iPhone 5 and an iPhone 5S.

**Comment by dakira** [comment]
@mkrautz Hi, can you please re-compile this with the current XCode and re-upload it the the AppStore? The current version on the AppStore crashes in iPhones 5S with iOS10. I'm currently circumventing this by re-compiling this myself every 7 days (free dev account). But I'd love to actually use it for real again. ;(

**Comment by mkrautz** [comment]
Sorry, I'll see what I can do.

Just to check -- the build in Git with current Xcode works just fine for you? No other problems?

**Comment by dakira** [comment]
@mkrautz There were a couple of warnings in the current version of xcode. I just applied the suggested fixes (automagically). If you want, I can send you a diff next time I boot into OSX.

**Comment by mkrautz** [comment]
No, I'm good. :-)

**Comment by mkrautz** [comment]
Sorry it had to take this long. A new version, 1.3.1, that is recompiled with the iOS 10 SDK is available on the App Store.

If that version still has issues, please open a new issue. Thanks!
